const StarActionTypes = {
  FETCH_STARS_SUCCESS: 'FETCH_STARS_SUCCESS',
  FETCH_STARS_START: 'FETCH_STARS_START',
  FETCH_STARS_FAIL: 'FETCH_STARS_FAIL',
  SET_STAR: 'SET_STAR',
};

export default StarActionTypes;
